config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'users#index'

resources :users do 
  resources :posts do 
    resources :likes 
    resources :comments 
  end 
end 
namespace :api do
  resources :users, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
      end
    end
  end  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :create, Post
      can :create, Comment
      can :update, Like
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  after_save :update_comment_count
  def update_comment_count
    post.increment!(:comments_counter)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_like_count
  def update_like_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_post_count

  def update_post_count
    author.increment!(:posts_counter)
  end

  def recent_comment
    comments.order(created_at: :desc).limit(3)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: Denylist

  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    Post.order(created_at: :desc).limit(3)
  end

  private

  # rubocop:disable all
  def jwt_payload
    super
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]

  def index
    posts = Post.find(params[:post_id])
    comments = posts.comments.includes(:author)
    render json: comments
  end

  def create
    posts = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id
    comment.post_id = posts.id

    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name bio photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comments = Comment.new
  end

  def create
    @current_post = Post.find(params[:post_id])
    @comments = @current_post.comments.new(comment_params)
    @comments.post_id = @current_post.id
    @comments.author_id = current_user.id
    if @comments.save
      redirect_to "/users/#{@current_post.author.id}/posts/#{@current_post.id}"
    else
      render :new
    end
  end

  def destroy
    @current_post = Post.find(params[:post_id])
    @current_comment = @current_post.comments.find(params[:id])
    @current_comment.destroy
    if @current_comment.destroy
      redirect_to user_post_path(@current_post.author_id, @current_post.id)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post_id = params[:post_id]
    if @like.save
      flash[:success] = 'You liked this post!'
      redirect_to "/users/#{params[:author_id]}/posts/#{params[:post_id]}"
    else
      flash[:danger] = 'Not able to like this post.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to "/users/#{current_user.id}/posts"
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy

    if @post.destroy
      redirect_to user_posts_path(current_user.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<div class='mt-5 d-flex align-items-center flex-column'>
  <h1>Enter your comment below: </h1>
  <%= form_with model: @comments, url: user_post_comments_path do |f| %>
    <div class='mb-3'>
      <%= f.text_area :text, size:"50x3",placeholder: 'Enter Your Comment', class:'form-control'%>
    </div>
    <%= f.submit "Comment", class:'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Here is a list of posts for a given user</h1>
<hr>

 <div class = "row ml-3 mb-4 ">
    <div class = "col-md-3">
     <img src = "<%= @user.photo %>" class = "ml-3 w-50" alt="profile">
    </div>

    <div class = "col-md-1"></div>

    <div class = "col-md-8 pl-3">
     <p><%= @user.name %> &nbsp Number of posts:<%=@user.posts_counter%></p>
    </div>
    </div>
    </div>
    <div>
    <%= link_to "Add New Post", new_user_post_path(user_id: @user.id), class:"btn btn-primary my-3" %>
    </div>

    <div class = "row">
    <div class = "row">
    <% @posts.each do |post| %>
    <%= link_to user_post_path(id: post.id), class:'nav-link' do%>
    <div class = "container-fluid mx-2 my-2 bg-secondary">
    <p>
    Post Id#:<%=post.id%><br>
    Post Text: <%=post.text%><br>
    Comment_counter:<%=post.comments_counter%><br>
    Likes_counter:<%=post.likes_counter%>
    </p>
    </div>
    <% end %>
    </div>
    </div>
    
    <div class = "row mb-2 ">
    <% post.recent_comment.includes(:author).each do |comment| %>
              <p class="card-text"><%= comment.author.name %>: <%= comment.text %></p>
            <% end %>
            <%end%>
    
    </div>
    </div>
    

app/views/posts/new.html.erb
<div>
<h1>Add new post</h1>
<%= form_with model: @post, url: user_posts_path do |form|%>
<div>
<%= form.text_field :title, placeholder:"Enter post title", class:"form-control w-25 "%>
<%= form.text_field :text, placeholder:"Enter text", class:"form-control w-25"%>
<%= form.submit "Add Post", class:"btn btn-primary w-25", data:{turbo:false}%>
</div>
<%end%>
</div>

app/views/posts/show.html.erb
<h1>Post</h1>

<div class = "row pl-3 border border-2 border-dark bg-secondary">
<div class = "col-md-4">
<p>Post#:&nbsp<%=@post.id%>&nbspBy: <%=@user.name%></p>
</div>
<div class = "col-md-4">
</div>
<div class = "col-md-4">
<p>Comment:<%=@post.comments_counter%> &nbsp Likes_counter: &nbsp<%=@post.likes_counter%> </p>
</div>
<div>
<p>Title: <%=@post.text%></p>
</div>
</div>

<%= form_with url: "/users/#{@post.author.id}/posts/#{@post.id}/likes" ,class: "col-6" do |form|%>
 <%= form.submit "like", class: "col-3 my-3"%>
  <% end %> 
  
  <% if can? :destroy, @post %>
     <%= link_to "Delete",user_post_path(id: @post.id), class:"btn btn-outline-danger", "data-turbo-method": :delete %>
  <% end %>
  

<div class = "row border border-2 border-dark">
<p>
 <% @comments.includes(:author).each do |comment| %>
              <p class="card-text"><%= comment.author.name %>: <%= comment.text %></p>
              
              <% if can? :destroy, comment %>
                      <%= link_to "Delete",user_post_comment_path(user_id:@user.id ,post_id:@post.id, id: comment.id), class:"btn btn-outline-danger", "data-turbo-method": :delete %>            <% end %>
              <% end %>
</p>

  <%= link_to "Add New Comment", new_user_post_comment_path(user_id: @user.id, post_id: @post.id), class:"btn btn-primary w-25" %>
</div>

app/views/users/index.html.erb
<h1>Here is list of users</h1>
<% @users.each do |user| %>
<%= link_to user_path(id: user.id), class:'nav-link' do%>
   <div class = "row ml-3 bg-secondary border border-dark mb-4 ">
    <div class = "col-md-3">
     <img src = "<%= user.photo %>" class = "ml-3 w-50" alt="profile">
    </div>
    <div class = "col-md-8 pl-3">
     <p><%= user.name %></p>
    <p>Posts-Counter: <%= user.posts_counter%></p>
    </div>
    </div>
     <% end %>
<% end %>

app/views/users/show.html.erb
<h1> User by Id</h1>


<div class = 'row'>
<div class = "col-md-3">
     <img src = "<%= @user.photo %>" class = "ml-3 w-50" alt="profile">
</div>
<div class = "col-md-8">
<%=@user.name%>
<p>Number of posts:</p>
<%=@user.posts_counter%>
</div>

<div class = "row border border-2 border-dark mt-2 mb-2 bg-secondary px-5">
Bio:&nbsp<%=@user.bio%>
</div>

<div>
  <% @user.recent_posts.each do |post| %>
<div class = "container-fluid mx-2 my-2">
  <div class = "row bg-secondary my-5">
      <%= link_to user_post_url(user_id:@user.id, id: post.id), class:'nav-link' do%>
      <p>ID: <%=post.id%>
      Title:<%=post.title%></P>
      <p>Text: <%=post.text%></p>
      <p>Comments_counter: <%=post.comments_counter%></p>
      <p>Likes_counter<%=post.likes_counter%></p>
        <% end %>
    <% end %>
    </div>
</div>
</div>
<div>
  <%= link_to "Show all Posts", user_posts_path(user_id: @user.id), class:"btn btn-primary mb-3" %>
  </div>
</div>